package com.camelot.pmt.project.model;

import java.util.Date;

public class Demand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_name
     *
     * @mbggenerated
     */
    private String demandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_code
     *
     * @mbggenerated
     */
    private String demandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_status
     *
     * @mbggenerated
     */
    private String demandStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_level
     *
     * @mbggenerated
     */
    private String demandLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_file
     *
     * @mbggenerated
     */
    private String demandFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_file_name
     *
     * @mbggenerated
     */
    private String demandFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_source
     *
     * @mbggenerated
     */
    private String demandSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.modify_user_id
     *
     * @mbggenerated
     */
    private String modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.Column_1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.Column_2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.Column_3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.Column_4
     *
     * @mbggenerated
     */
    private String column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.Column_5
     *
     * @mbggenerated
     */
    private String column5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.id
     *
     * @return the value of demand.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.id
     *
     * @param id the value for demand.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.pid
     *
     * @return the value of demand.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.pid
     *
     * @param pid the value for demand.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.project_id
     *
     * @return the value of demand.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.project_id
     *
     * @param projectId the value for demand.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_name
     *
     * @return the value of demand.demand_name
     *
     * @mbggenerated
     */
    public String getDemandName() {
        return demandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_name
     *
     * @param demandName the value for demand.demand_name
     *
     * @mbggenerated
     */
    public void setDemandName(String demandName) {
        this.demandName = demandName == null ? null : demandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_code
     *
     * @return the value of demand.demand_code
     *
     * @mbggenerated
     */
    public String getDemandCode() {
        return demandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_code
     *
     * @param demandCode the value for demand.demand_code
     *
     * @mbggenerated
     */
    public void setDemandCode(String demandCode) {
        this.demandCode = demandCode == null ? null : demandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_status
     *
     * @return the value of demand.demand_status
     *
     * @mbggenerated
     */
    public String getDemandStatus() {
        return demandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_status
     *
     * @param demandStatus the value for demand.demand_status
     *
     * @mbggenerated
     */
    public void setDemandStatus(String demandStatus) {
        this.demandStatus = demandStatus == null ? null : demandStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_level
     *
     * @return the value of demand.demand_level
     *
     * @mbggenerated
     */
    public String getDemandLevel() {
        return demandLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_level
     *
     * @param demandLevel the value for demand.demand_level
     *
     * @mbggenerated
     */
    public void setDemandLevel(String demandLevel) {
        this.demandLevel = demandLevel == null ? null : demandLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_file
     *
     * @return the value of demand.demand_file
     *
     * @mbggenerated
     */
    public String getDemandFile() {
        return demandFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_file
     *
     * @param demandFile the value for demand.demand_file
     *
     * @mbggenerated
     */
    public void setDemandFile(String demandFile) {
        this.demandFile = demandFile == null ? null : demandFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_file_name
     *
     * @return the value of demand.demand_file_name
     *
     * @mbggenerated
     */
    public String getDemandFileName() {
        return demandFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_file_name
     *
     * @param demandFileName the value for demand.demand_file_name
     *
     * @mbggenerated
     */
    public void setDemandFileName(String demandFileName) {
        this.demandFileName = demandFileName == null ? null : demandFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_source
     *
     * @return the value of demand.demand_source
     *
     * @mbggenerated
     */
    public String getDemandSource() {
        return demandSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_source
     *
     * @param demandSource the value for demand.demand_source
     *
     * @mbggenerated
     */
    public void setDemandSource(String demandSource) {
        this.demandSource = demandSource == null ? null : demandSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.create_time
     *
     * @return the value of demand.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.create_time
     *
     * @param createTime the value for demand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.modify_time
     *
     * @return the value of demand.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.modify_time
     *
     * @param modifyTime the value for demand.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.create_user_id
     *
     * @return the value of demand.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.create_user_id
     *
     * @param createUserId the value for demand.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.modify_user_id
     *
     * @return the value of demand.modify_user_id
     *
     * @mbggenerated
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.modify_user_id
     *
     * @param modifyUserId the value for demand.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.Column_1
     *
     * @return the value of demand.Column_1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.Column_1
     *
     * @param column1 the value for demand.Column_1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.Column_2
     *
     * @return the value of demand.Column_2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.Column_2
     *
     * @param column2 the value for demand.Column_2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.Column_3
     *
     * @return the value of demand.Column_3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.Column_3
     *
     * @param column3 the value for demand.Column_3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.Column_4
     *
     * @return the value of demand.Column_4
     *
     * @mbggenerated
     */
    public String getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.Column_4
     *
     * @param column4 the value for demand.Column_4
     *
     * @mbggenerated
     */
    public void setColumn4(String column4) {
        this.column4 = column4 == null ? null : column4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.Column_5
     *
     * @return the value of demand.Column_5
     *
     * @mbggenerated
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.Column_5
     *
     * @param column5 the value for demand.Column_5
     *
     * @mbggenerated
     */
    public void setColumn5(String column5) {
        this.column5 = column5 == null ? null : column5.trim();
    }
}