package com.camelot.pmt.project.model;

public class DemandWithBLOBs extends Demand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.demand_desc
     *
     * @mbggenerated
     */
    private String demandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.check_standard
     *
     * @mbggenerated
     */
    private String checkStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.close_reason
     *
     * @mbggenerated
     */
    private String closeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.source_remark
     *
     * @mbggenerated
     */
    private String sourceRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.demand_desc
     *
     * @return the value of demand.demand_desc
     *
     * @mbggenerated
     */
    public String getDemandDesc() {
        return demandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.demand_desc
     *
     * @param demandDesc the value for demand.demand_desc
     *
     * @mbggenerated
     */
    public void setDemandDesc(String demandDesc) {
        this.demandDesc = demandDesc == null ? null : demandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.check_standard
     *
     * @return the value of demand.check_standard
     *
     * @mbggenerated
     */
    public String getCheckStandard() {
        return checkStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.check_standard
     *
     * @param checkStandard the value for demand.check_standard
     *
     * @mbggenerated
     */
    public void setCheckStandard(String checkStandard) {
        this.checkStandard = checkStandard == null ? null : checkStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.close_reason
     *
     * @return the value of demand.close_reason
     *
     * @mbggenerated
     */
    public String getCloseReason() {
        return closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.close_reason
     *
     * @param closeReason the value for demand.close_reason
     *
     * @mbggenerated
     */
    public void setCloseReason(String closeReason) {
        this.closeReason = closeReason == null ? null : closeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.source_remark
     *
     * @return the value of demand.source_remark
     *
     * @mbggenerated
     */
    public String getSourceRemark() {
        return sourceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.source_remark
     *
     * @param sourceRemark the value for demand.source_remark
     *
     * @mbggenerated
     */
    public void setSourceRemark(String sourceRemark) {
        this.sourceRemark = sourceRemark == null ? null : sourceRemark.trim();
    }
}