package com.camelot.pmt.project.mapper;

import com.camelot.pmt.project.model.Demand;
import com.camelot.pmt.project.model.DemandWithBLOBs;

public interface DemandMapper {
    /**
     *根据主键删除
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     *添加
     * @mbggenerated
     */
    int insert(DemandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbggenerated
     */
    int insertSelective(DemandWithBLOBs record);

    /**
     *根据主键查询
     * @mbggenerated
     */
    DemandWithBLOBs selectByPrimaryKey(Long id);

    /**
     *更新
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DemandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Demand record);
}