package com.camelot.pmt.testmanage.casemanage.mapper;

import com.camelot.pmt.testmanage.casemanage.model.UseCaseDetail;

import java.util.List;

public interface UseCaseDetailMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_procedure_implement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_procedure_implement
     *
     * @mbg.generated
     */
    int insert(UseCaseDetail record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_procedure_implement
     *
     * @mbg.generated
     */
    int insertSelective(UseCaseDetail record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_detail
     *
     * @mbg.generated
     */
    UseCaseDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UseCaseDetail record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UseCaseDetail record);

    int insertBatch(List<UseCaseDetail> list);

    List<UseCaseDetail> queryUseCaseProcedureImplementd(Long implementId);
}