package com.camelot.pmt.testmanage.casemanage.mapper;

import java.util.List;
import java.util.Map;

import com.camelot.pmt.testmanage.casemanage.model.UseCaseHistory;

public interface UseCaseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    int insert(UseCaseHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    int insertSelective(UseCaseHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    UseCaseHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    int updateByPrimaryKeySelective(UseCaseHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table use_case_history
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    int updateByPrimaryKey(UseCaseHistory record);

    List<Map<String, Object>> queryByuseHistory(Long id);
}