package com.camelot.pmt.testmanage.casemanage.model;

import java.util.Date;

public class UseCaseHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_history.id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_history.createTime
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_history.operation_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    private String operationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_history.operation_function
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    private String operationFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_history.use_case_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    private Long useCaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_history.id
     *
     * @return the value of use_case_history.id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_history.id
     *
     * @param id the value for use_case_history.id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_history.createTime
     *
     * @return the value of use_case_history.createTime
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_history.createTime
     *
     * @param createtime the value for use_case_history.createTime
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_history.operation_id
     *
     * @return the value of use_case_history.operation_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_history.operation_id
     *
     * @param operationId the value for use_case_history.operation_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public void setOperationId(String operationId) {
        this.operationId = operationId == null ? null : operationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_history.operation_function
     *
     * @return the value of use_case_history.operation_function
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public String getOperationFunction() {
        return operationFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_history.operation_function
     *
     * @param operationFunction the value for use_case_history.operation_function
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public void setOperationFunction(String operationFunction) {
        this.operationFunction = operationFunction == null ? null : operationFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_history.use_case_id
     *
     * @return the value of use_case_history.use_case_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public Long getUseCaseId() {
        return useCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_history.use_case_id
     *
     * @param useCaseId the value for use_case_history.use_case_id
     *
     * @mbggenerated Thu Apr 19 15:22:54 CST 2018
     */
    public void setUseCaseId(Long useCaseId) {
        this.useCaseId = useCaseId;
    }
}