package com.camelot.pmt.testmanage.casemanage.model;

public class UseCaseProcedureImplement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.implement_id
     *
     * @mbg.generated
     */
    private Long implementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.procedure_name
     *
     * @mbg.generated
     */
    private String procedureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.test_result
     *
     * @mbg.generated
     */
    private String testResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.anticipate
     *
     * @mbg.generated
     */
    private String anticipate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_case_procedure_implement.version_id
     *
     * @mbg.generated
     */
    private String versionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.id
     *
     * @return the value of use_case_procedure_implement.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.id
     *
     * @param id the value for use_case_procedure_implement.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.implement_id
     *
     * @return the value of use_case_procedure_implement.implement_id
     *
     * @mbg.generated
     */
    public Long getImplementId() {
        return implementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.implement_id
     *
     * @param implementId the value for use_case_procedure_implement.implement_id
     *
     * @mbg.generated
     */
    public void setImplementId(Long implementId) {
        this.implementId = implementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.procedure_name
     *
     * @return the value of use_case_procedure_implement.procedure_name
     *
     * @mbg.generated
     */
    public String getProcedureName() {
        return procedureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.procedure_name
     *
     * @param procedureName the value for use_case_procedure_implement.procedure_name
     *
     * @mbg.generated
     */
    public void setProcedureName(String procedureName) {
        this.procedureName = procedureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.test_result
     *
     * @return the value of use_case_procedure_implement.test_result
     *
     * @mbg.generated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.test_result
     *
     * @param testResult the value for use_case_procedure_implement.test_result
     *
     * @mbg.generated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.description
     *
     * @return the value of use_case_procedure_implement.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.description
     *
     * @param description the value for use_case_procedure_implement.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.anticipate
     *
     * @return the value of use_case_procedure_implement.anticipate
     *
     * @mbg.generated
     */
    public String getAnticipate() {
        return anticipate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.anticipate
     *
     * @param anticipate the value for use_case_procedure_implement.anticipate
     *
     * @mbg.generated
     */
    public void setAnticipate(String anticipate) {
        this.anticipate = anticipate == null ? null : anticipate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_case_procedure_implement.version_id
     *
     * @return the value of use_case_procedure_implement.version_id
     *
     * @mbg.generated
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_case_procedure_implement.version_id
     *
     * @param versionId the value for use_case_procedure_implement.version_id
     *
     * @mbg.generated
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }
}