package com.camelot.pmt.caserepertory.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.camelot.pmt.caserepertory.model.CaseRepertoryStep;
@Mapper
public interface CaseRepertoryStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int insert(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int insertSelective(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    CaseRepertoryStep selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseRepertoryStep record);
}