package com.camelot.pmt.caserepertory.mapper;

import com.camelot.pmt.caserepertory.model.CaseRepertoryStep;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;
@Mapper
public interface CaseRepertoryStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int insert(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int insertSelective(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    CaseRepertoryStep selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseRepertoryStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseRepertoryStep record);

    int insertBatch(List<CaseRepertoryStep> list);

    List<CaseRepertoryStep> findByUseCaseId(Long useCaseId);

    int remove(Map<String, Object> param);
}