package com.camelot.pmt.caserepertory.mapper;

import com.camelot.pmt.caserepertory.model.CaseRepertory;
import com.camelot.pmt.testmanage.bugmanage.model.SelectBugManage;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;
@Mapper
public interface CaseRepertoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    int insert(CaseRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    int insertSelective(CaseRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    CaseRepertory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_repertory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseRepertory record);

	List<SelectBugManage> selectCondition(Map<String, Object> map);

    int insertBatch(List<CaseRepertory> list);

    List<CaseRepertory> find(Map<String, Object> param);

    int remove(Map<String, Object> param);
}