package com.camelot.pmt.warning.mapper;

import com.camelot.pmt.warning.model.BugWarning;

public interface BugWarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    int insert(BugWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    int insertSelective(BugWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    BugWarning selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    int updateByPrimaryKeySelective(BugWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_warning
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    int updateByPrimaryKey(BugWarning record);
    
    
    Integer queryBugCount(Long projectId);
}