package com.camelot.pmt.warning.model;

import java.util.Date;

public class BugWarning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_warning.id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_warning.role_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_warning.project_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_warning.create_time
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_warning.num
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_warning.id
     *
     * @return the value of bug_warning.id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_warning.id
     *
     * @param id the value for bug_warning.id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_warning.role_id
     *
     * @return the value of bug_warning.role_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_warning.role_id
     *
     * @param roleId the value for bug_warning.role_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_warning.project_id
     *
     * @return the value of bug_warning.project_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_warning.project_id
     *
     * @param projectId the value for bug_warning.project_id
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_warning.create_time
     *
     * @return the value of bug_warning.create_time
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_warning.create_time
     *
     * @param createTime the value for bug_warning.create_time
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_warning.num
     *
     * @return the value of bug_warning.num
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_warning.num
     *
     * @param num the value for bug_warning.num
     *
     * @mbggenerated Tue Apr 24 10:08:32 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}