package com.camelot.pmt.caserepertory.model;

import org.hibernate.validator.constraints.NotBlank;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.Date;

public class CaseRepertory {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.case_title
     *
     * @mbg.generated
     */
    @NotBlank(message = "用例库标题不能为空")
    private String caseTitle;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.case_type
     *
     * @mbg.generated
     */
    private String caseType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.apply_phase
     *
     * @mbg.generated
     */
    private String applyPhase;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.num
     *
     * @mbg.generated
     */
    private String num;

    private String createUserId;
    private Date createTime;
    private String modifyUserId;
    private Date modifyTime;
    private String module;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory.precondition
     *
     * @mbg.generated
     */
    private String precondition;
    @Valid
    private List<CaseRepertoryStep> detail;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.id
     *
     * @return the value of case_repertory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.id
     *
     * @param id
     *            the value for case_repertory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.case_title
     *
     * @return the value of case_repertory.case_title
     *
     * @mbg.generated
     */
    public String getCaseTitle() {
        return caseTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.case_title
     *
     * @param caseTitle
     *            the value for case_repertory.case_title
     *
     * @mbg.generated
     */
    public void setCaseTitle(String caseTitle) {
        this.caseTitle = caseTitle == null ? null : caseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.case_type
     *
     * @return the value of case_repertory.case_type
     *
     * @mbg.generated
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.case_type
     *
     * @param caseType
     *            the value for case_repertory.case_type
     *
     * @mbg.generated
     */
    public void setCaseType(String caseType) {
        this.caseType = caseType == null ? null : caseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.description
     *
     * @return the value of case_repertory.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.description
     *
     * @param description
     *            the value for case_repertory.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.apply_phase
     *
     * @return the value of case_repertory.apply_phase
     *
     * @mbg.generated
     */
    public String getApplyPhase() {
        return applyPhase;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.apply_phase
     *
     * @param applyPhase
     *            the value for case_repertory.apply_phase
     *
     * @mbg.generated
     */
    public void setApplyPhase(String applyPhase) {
        this.applyPhase = applyPhase == null ? null : applyPhase.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.num
     *
     * @return the value of case_repertory.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.num
     *
     * @param num
     *            the value for case_repertory.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory.precondition
     *
     * @return the value of case_repertory.precondition
     *
     * @mbg.generated
     */
    public String getPrecondition() {
        return precondition;
    }

    public String getCreateUserId() {
        return createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getModifyUserId() {
        return modifyUserId;
    }

    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory.precondition
     *
     * @param precondition
     *            the value for case_repertory.precondition
     *
     * @mbg.generated
     */

    public void setPrecondition(String precondition) {
        this.precondition = precondition == null ? null : precondition.trim();
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public List<CaseRepertoryStep> getDetail() {
        return detail;
    }

    public void setDetail(List<CaseRepertoryStep> detail) {
        this.detail = detail;
    }
}