package com.camelot.pmt.caserepertory.model;

import org.hibernate.validator.constraints.NotBlank;

public class CaseRepertoryStep {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory_step.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory_step.step
     *
     * @mbg.generated
     */
    @NotBlank(message = "步骤名称不能为空")
    private String step;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory_step.expect
     *
     * @mbg.generated
     */
    private String expect;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column case_repertory_step.use_case_id
     *
     * @mbg.generated
     */
    private Long useCaseId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory_step.id
     *
     * @return the value of case_repertory_step.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory_step.id
     *
     * @param id
     *            the value for case_repertory_step.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory_step.step
     *
     * @return the value of case_repertory_step.step
     *
     * @mbg.generated
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory_step.step
     *
     * @param step
     *            the value for case_repertory_step.step
     *
     * @mbg.generated
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory_step.expect
     *
     * @return the value of case_repertory_step.expect
     *
     * @mbg.generated
     */
    public String getExpect() {
        return expect;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory_step.expect
     *
     * @param expect
     *            the value for case_repertory_step.expect
     *
     * @mbg.generated
     */
    public void setExpect(String expect) {
        this.expect = expect == null ? null : expect.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column case_repertory_step.use_case_id
     *
     * @return the value of case_repertory_step.use_case_id
     *
     * @mbg.generated
     */
    public Long getUseCaseId() {
        return useCaseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column case_repertory_step.use_case_id
     *
     * @param useCaseId
     *            the value for case_repertory_step.use_case_id
     *
     * @mbg.generated
     */
    public void setUseCaseId(Long useCaseId) {
        this.useCaseId = useCaseId;
    }
}